name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-dotnet@master
    - name: Build solution
      run: dotnet build
    - name: Run tests
      run: dotnet test --no-build
